WIP FiX ECS AMI test

diff --git a/ci/meta.yml b/ci/meta.yml
--- a/ci/meta.yml
+++ b/ci/meta.yml
@@ -230,6 +230,69 @@ meta:
         outputs:
           - name: terraform-success
 
+    terminate-ecs-instances:
+      task: terminate-ecs-instances
+      config:
+        platform: linux
+        image_resource:
+          type: docker-image
+          source:
+            repository: ((dataworks.docker_awscli_repository))
+            version: ((dataworks.docker_awscli_version))
+            tag: ((dataworks.docker_awscli_version))
+        run:
+          path: sh
+          args:
+            - -exc
+            - |
+              export AWS_DEFAULT_REGION
+              ami_id=$(cat dw-al2-ecs-ami/id)
+              source /assume-role
+              set -x
+
+              instance_ids=$(aws ec2 describe-instances --filters Name=tag:Name,Values=metrics-ecs-cluster-* Name=instance-state-name,Values=running | jq -r '.Reservations[].Instances[].InstanceId')
+              echo $instance_ids
+              exit 0
+
+              for instance_id in $instance_ids;
+                do
+                  aws ec2 terminate-instances --instance-ids "$instance_id"
+                done;
+
+              desired_capacity=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-name "$ASG_NAME" | jq -r '.AutoScalingGroups[0].DesiredCapacity')
+
+              count=0
+              max_retries="$MAX_RETRIES"
+
+              while [ "$count" -lt "$max_retries" ]
+                do
+                  sleep "$SLEEP_TIME"
+                  instance_ids=$(aws ec2 describe-instances --filters Name=tag:Name,Values=metrics-ecs-cluster-* Name=instance-state-name,Values=running | jq -r '.Reservations[].Instances[].InstanceId')
+                  instance_count=$(echo "${#instance_ids[@]}")
+                  if [[ $instance_count -eq $desired_capacity ]]; then
+                    image_ids="$(aws ec2 describe-instances --instance-ids $instance_ids | jq -r '.Reservations[] | .Instances[] | .ImageId')"
+                    for i in $image_ids; do
+                      if [ ! "$i" -eq "$ami_id" ]; then
+                        echo "Instance found with wrong AMI ID, Exiting..."
+                        exit 1
+                      fi;
+                    done;
+                    echo "All desired instances are running untested AMI, Exiting with success..."
+                    exit 0
+                  fi;
+                  let "count+=1"
+                done;
+              echo "Cluster was unable to start desired instances with untested AMI in expected timeframe, Exiting with error..."
+              exit 1
+        inputs:
+          - name: dw-al2-ecs-ami
+      params:
+        AWS_DEFAULT_REGION: ((dataworks.aws_region))
+        AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
+        ASG_NAME: metrics-cluster
+        SLEEP_TIME: 60
+        MAX_RETRIES: 10
+
     test-ecs-ami:
       task: test-ecs-ami
       config:
@@ -249,7 +312,7 @@ meta:
               source /assume-role
               set +x
               max_retries=5
-              task_json="$(aws ecs run-task --cluster "$CLUSTER_NAME" --task-definition test_ecs_ami --overrides "{\"containerOverrides\": [{\"name\": \"test-ecs-ami\", \"command\": [\"sh\", \"-c\", \"sleep 300\"]}]}")"
+              task_json="$(aws ecs run-task --cluster "$CLUSTER_NAME" --capacity-provider-strategy=metrics-cluster --task-definition test_ecs_ami --overrides "{\"containerOverrides\": [{\"name\": \"test-ecs-ami\", \"command\": [\"sh\", \"-c\", \"sleep 300\"]}]}")"
               task_arn=$(echo $task_json | jq -r '.tasks[0].taskArn')
               while [ $max_retries > 0 ]
               do
